version: '3.6'

services:

  botje-scryfall:
    build:
      context: .
      dockerfile: ./Botje.Mtg.Api/Dockerfile
    environment:
      - SCRYFALL_BOTJE-LOGGING_ACCESS_KEY=test-key-for-debug
    networks:
      - traefik-public
    ports:
      - 45000:80
      - 45001:443

networks:
  traefik-public:
    external: true