name: Docker Image CI

env:
  IMAGE_NAME: "madailei/scryfall-slack-botje"
  DOCKERFILE_PATH: "./Botje.Mtg.Api/Dockerfile"

on:
  push:
    # branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**/docker-compose*.yaml'
      - '**/GitHubWorkflows/**'
#  pull_request:
#    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Test
      run: |
        dotnet test
  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2  
    - name: Build and push Docker image
      run: |
        ls -la
        dockerImageTag="${{ env.IMAGE_NAME }}:0.0.0-continuous-$(date +'%Y-%m-%d')-epoch-$(date +'%s')"
        echo $dockerImageTag
        docker build . --file ${{ env.DOCKERFILE_PATH }} --tag $dockerImageTag
        docker login -u madailei -p ${{ secrets.DOCKER_SECRET }}
        docker image push $dockerImageTag
