name: Docker Image CI

env:
  IMAGE_NAME: "madailei/scryfall-slack-botje"

on:
  push:
    # branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Build and push Docker image
      run: |
        dockerImageTag="${{ env.IMAGE_NAME }}:continuous-$(date +'%Y-%m-%d')-epoch-$(date +'%s')"
        echo $dockerImageTag
        docker build . --file Dockerfile --tag $dockerImageTag
        docker login -u madailei -p ${{ secrets.DOCKER_SECRET }}
        docker image push $dockerImageTag
